# SPDX-License-Identifier: CeCILL-2.1 OR AGPL-3.0-or-later
"""On-disk catalogue access: discovery, descriptor loading, and the bundled copy.

A *catalogue root* is a directory containing ``pipelines/<id>/`` bundles and a
``catalog/index.json`` registry. The same reader serves a working checkout, the
wheel-bundled copy under ``nirs4all_repository/_catalog/``, and a materialised cache
entry.
"""

from __future__ import annotations

import json
from importlib import resources
from pathlib import Path

import yaml

from .schema import PipelineDescriptor

PIPELINES_DIRNAME = "pipelines"
CATALOG_DIRNAME = "catalog"
INDEX_FILENAME = "index.json"
DESCRIPTOR_FILENAME = "descriptor.yaml"
CARD_FILENAME = "card.md"
MANIFEST_FILENAME = "manifest.json"
ROCRATE_FILENAME = "ro-crate-metadata.json"

#: Filenames generated by ``build`` (never part of a bundle's own checksum set).
GENERATED_FILES = frozenset({MANIFEST_FILENAME, ROCRATE_FILENAME})


class CatalogError(Exception):
    """Raised when a catalogue or pipeline cannot be located or read."""


class PipelineNotFound(CatalogError):
    """Raised when a pipeline id is not present in a catalogue."""


def detect_root(explicit: Path | None = None) -> Path | None:
    """Return a catalogue checkout root, or ``None`` if not running inside one.

    Resolution: *explicit* argument → walk up from the current directory looking for a
    directory that has both ``pipelines/`` and ``catalog/``.
    """
    if explicit is not None:
        return Path(explicit)
    here = Path.cwd().resolve()
    for candidate in (here, *here.parents):
        if (candidate / PIPELINES_DIRNAME).is_dir() and (candidate / CATALOG_DIRNAME).is_dir():
            return candidate
    return None


def bundled_root() -> Path | None:
    """Return the wheel-bundled catalogue root, or ``None`` if not packaged."""
    try:
        anchor = resources.files("nirs4all_repository") / "_catalog"
    except (ModuleNotFoundError, FileNotFoundError):
        return None
    path = Path(str(anchor))
    return path if (path / PIPELINES_DIRNAME).is_dir() else None


def pipelines_dir(root: Path) -> Path:
    """Return the ``pipelines/`` directory of a catalogue *root*."""
    return root / PIPELINES_DIRNAME


def pipeline_dir(root: Path, pipeline_id: str) -> Path:
    """Return the bundle directory for *pipeline_id* under *root*."""
    return pipelines_dir(root) / pipeline_id


def index_path(root: Path) -> Path:
    """Return the path to ``catalog/index.json`` under *root*."""
    return root / CATALOG_DIRNAME / INDEX_FILENAME


def list_pipeline_ids(root: Path) -> list[str]:
    """Return the sorted ids of every pipeline bundle under *root*."""
    base = pipelines_dir(root)
    if not base.is_dir():
        return []
    return sorted(p.name for p in base.iterdir() if p.is_dir() and (p / DESCRIPTOR_FILENAME).is_file())


def load_descriptor_file(path: Path) -> PipelineDescriptor:
    """Load and validate a ``descriptor.yaml`` at *path*."""
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise CatalogError(f"descriptor {path} is not a mapping")
    return PipelineDescriptor.model_validate(data)


def load_descriptor(root: Path, pipeline_id: str) -> PipelineDescriptor:
    """Load the descriptor for *pipeline_id* under *root*."""
    path = pipeline_dir(root, pipeline_id) / DESCRIPTOR_FILENAME
    if not path.is_file():
        raise PipelineNotFound(f"pipeline {pipeline_id!r} not found under {root}")
    descriptor = load_descriptor_file(path)
    if descriptor.id != pipeline_id:
        raise CatalogError(f"descriptor id {descriptor.id!r} != directory name {pipeline_id!r}")
    return descriptor


def load_index(root: Path) -> dict:
    """Load ``catalog/index.json`` from *root*."""
    path = index_path(root)
    if not path.is_file():
        raise CatalogError(f"index.json not found at {path}")
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise CatalogError(f"index.json at {path} is not a JSON object")
    return data


def data_files(pipeline_path: Path, descriptor: PipelineDescriptor) -> list[Path]:
    """Return the ordered list of *data files* of a bundle (excludes generated manifests).

    Data files = ``descriptor.yaml`` + the recipe + ``card.md`` (if present) + every
    declared inline artifact. The generated ``manifest.json``/``ro-crate-metadata.json``
    are deliberately excluded so checksum coverage is never self-referential.
    """
    files = [pipeline_path / DESCRIPTOR_FILENAME, pipeline_path / descriptor.recipe.path]
    card = pipeline_path / CARD_FILENAME
    if card.is_file():
        files.append(card)
    for artifact in descriptor.artifacts:
        blob = pipeline_path / artifact.relpath
        if blob.is_file():
            files.append(blob)
    # De-duplicate while preserving order.
    seen: set[Path] = set()
    ordered: list[Path] = []
    for path in files:
        if path not in seen:
            seen.add(path)
            ordered.append(path)
    return ordered
